// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateIssuer) DeepCopyInto(out *CertificateIssuer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateIssuer.
func (in *CertificateIssuer) DeepCopy() *CertificateIssuer {
	if in == nil {
		return nil
	}
	out := new(CertificateIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionManager) DeepCopyInto(out *ConnectionManager) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionManager.
func (in *ConnectionManager) DeepCopy() *ConnectionManager {
	if in == nil {
		return nil
	}
	out := new(ConnectionManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletService) DeepCopyInto(out *KlusterletService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletService.
func (in *KlusterletService) DeepCopy() *KlusterletService {
	if in == nil {
		return nil
	}
	out := new(KlusterletService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlusterletService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletServiceList) DeepCopyInto(out *KlusterletServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KlusterletService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletServiceList.
func (in *KlusterletServiceList) DeepCopy() *KlusterletServiceList {
	if in == nil {
		return nil
	}
	out := new(KlusterletServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlusterletServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletServiceSpec) DeepCopyInto(out *KlusterletServiceSpec) {
	*out = *in
	out.ConnectionManager = in.ConnectionManager
	out.CertificateIssuer = in.CertificateIssuer
	out.Search = in.Search
	out.WorkManager = in.WorkManager
	out.PolicyController = in.PolicyController
	out.ServiceRegistry = in.ServiceRegistry
	out.TopologyCollector = in.TopologyCollector
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletServiceSpec.
func (in *KlusterletServiceSpec) DeepCopy() *KlusterletServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KlusterletServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletServiceStatus) DeepCopyInto(out *KlusterletServiceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletServiceStatus.
func (in *KlusterletServiceStatus) DeepCopy() *KlusterletServiceStatus {
	if in == nil {
		return nil
	}
	out := new(KlusterletServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyController) DeepCopyInto(out *PolicyController) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyController.
func (in *PolicyController) DeepCopy() *PolicyController {
	if in == nil {
		return nil
	}
	out := new(PolicyController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Search) DeepCopyInto(out *Search) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Search.
func (in *Search) DeepCopy() *Search {
	if in == nil {
		return nil
	}
	out := new(Search)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistry) DeepCopyInto(out *ServiceRegistry) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistry.
func (in *ServiceRegistry) DeepCopy() *ServiceRegistry {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyCollector) DeepCopyInto(out *TopologyCollector) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyCollector.
func (in *TopologyCollector) DeepCopy() *TopologyCollector {
	if in == nil {
		return nil
	}
	out := new(TopologyCollector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManager) DeepCopyInto(out *WorkManager) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManager.
func (in *WorkManager) DeepCopy() *WorkManager {
	if in == nil {
		return nil
	}
	out := new(WorkManager)
	in.DeepCopyInto(out)
	return out
}
