// IBM Confidential
// OCO Source Materials
// 5737-E67
// (C) Copyright IBM Corporation 2019 All Rights Reserved
// The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManager) DeepCopyInto(out *CertManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManager.
func (in *CertManager) DeepCopy() *CertManager {
	if in == nil {
		return nil
	}
	out := new(CertManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerList) DeepCopyInto(out *CertManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerList.
func (in *CertManagerList) DeepCopy() *CertManagerList {
	if in == nil {
		return nil
	}
	out := new(CertManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerServiceAccount) DeepCopyInto(out *CertManagerServiceAccount) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerServiceAccount.
func (in *CertManagerServiceAccount) DeepCopy() *CertManagerServiceAccount {
	if in == nil {
		return nil
	}
	out := new(CertManagerServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpec) DeepCopyInto(out *CertManagerSpec) {
	*out = *in
	out.ServiceAccount = in.ServiceAccount
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpec.
func (in *CertManagerSpec) DeepCopy() *CertManagerSpec {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerStatus) DeepCopyInto(out *CertManagerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerStatus.
func (in *CertManagerStatus) DeepCopy() *CertManagerStatus {
	if in == nil {
		return nil
	}
	out := new(CertManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionManager) DeepCopyInto(out *ConnectionManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionManager.
func (in *ConnectionManager) DeepCopy() *ConnectionManager {
	if in == nil {
		return nil
	}
	out := new(ConnectionManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectionManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionManagerList) DeepCopyInto(out *ConnectionManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConnectionManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionManagerList.
func (in *ConnectionManagerList) DeepCopy() *ConnectionManagerList {
	if in == nil {
		return nil
	}
	out := new(ConnectionManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectionManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionManagerSpec) DeepCopyInto(out *ConnectionManagerSpec) {
	*out = *in
	if in.BootStrapConfig != nil {
		in, out := &in.BootStrapConfig, &out.BootStrapConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionManagerSpec.
func (in *ConnectionManagerSpec) DeepCopy() *ConnectionManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionManagerStatus) DeepCopyInto(out *ConnectionManagerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionManagerStatus.
func (in *ConnectionManagerStatus) DeepCopy() *ConnectionManagerStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectionManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreDNS) DeepCopyInto(out *CoreDNS) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreDNS.
func (in *CoreDNS) DeepCopy() *CoreDNS {
	if in == nil {
		return nil
	}
	out := new(CoreDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployableConfig) DeepCopyInto(out *DeployableConfig) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployableConfig.
func (in *DeployableConfig) DeepCopy() *DeployableConfig {
	if in == nil {
		return nil
	}
	out := new(DeployableConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletConnectionManagerSpec) DeepCopyInto(out *KlusterletConnectionManagerSpec) {
	*out = *in
	if in.BootStrapConfig != nil {
		in, out := &in.BootStrapConfig, &out.BootStrapConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletConnectionManagerSpec.
func (in *KlusterletConnectionManagerSpec) DeepCopy() *KlusterletConnectionManagerSpec {
	if in == nil {
		return nil
	}
	out := new(KlusterletConnectionManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletCoreDNSConfig) DeepCopyInto(out *KlusterletCoreDNSConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletCoreDNSConfig.
func (in *KlusterletCoreDNSConfig) DeepCopy() *KlusterletCoreDNSConfig {
	if in == nil {
		return nil
	}
	out := new(KlusterletCoreDNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletOverride) DeepCopyInto(out *KlusterletOverride) {
	*out = *in
	in.CertManager.DeepCopyInto(&out.CertManager)
	in.ConnectionManager.DeepCopyInto(&out.ConnectionManager)
	in.SearchCollector.DeepCopyInto(&out.SearchCollector)
	in.ServiceRegistry.DeepCopyInto(&out.ServiceRegistry)
	in.WorkManager.DeepCopyInto(&out.WorkManager)
	in.Tiller.DeepCopyInto(&out.Tiller)
	in.TopologyCollector.DeepCopyInto(&out.TopologyCollector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletOverride.
func (in *KlusterletOverride) DeepCopy() *KlusterletOverride {
	if in == nil {
		return nil
	}
	out := new(KlusterletOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletPrometheusIntegrationSpec) DeepCopyInto(out *KlusterletPrometheusIntegrationSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletPrometheusIntegrationSpec.
func (in *KlusterletPrometheusIntegrationSpec) DeepCopy() *KlusterletPrometheusIntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(KlusterletPrometheusIntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletSearchCollectorSpec) DeepCopyInto(out *KlusterletSearchCollectorSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletSearchCollectorSpec.
func (in *KlusterletSearchCollectorSpec) DeepCopy() *KlusterletSearchCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(KlusterletSearchCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletService) DeepCopyInto(out *KlusterletService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletService.
func (in *KlusterletService) DeepCopy() *KlusterletService {
	if in == nil {
		return nil
	}
	out := new(KlusterletService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlusterletService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletServiceList) DeepCopyInto(out *KlusterletServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KlusterletService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletServiceList.
func (in *KlusterletServiceList) DeepCopy() *KlusterletServiceList {
	if in == nil {
		return nil
	}
	out := new(KlusterletServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlusterletServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletServiceRegistrySpec) DeepCopyInto(out *KlusterletServiceRegistrySpec) {
	*out = *in
	out.CoreDNS = in.CoreDNS
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletServiceRegistrySpec.
func (in *KlusterletServiceRegistrySpec) DeepCopy() *KlusterletServiceRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(KlusterletServiceRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletServiceSpec) DeepCopyInto(out *KlusterletServiceSpec) {
	*out = *in
	if in.ClusterLabels != nil {
		in, out := &in.ClusterLabels, &out.ClusterLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.BootStrapConfig != nil {
		in, out := &in.BootStrapConfig, &out.BootStrapConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.TillerIntegration = in.TillerIntegration
	out.PrometheusIntegration = in.PrometheusIntegration
	out.TopologyCollectorConfig = in.TopologyCollectorConfig
	out.SearchCollectorConfig = in.SearchCollectorConfig
	out.ServiceRegistryConfig = in.ServiceRegistryConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletServiceSpec.
func (in *KlusterletServiceSpec) DeepCopy() *KlusterletServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KlusterletServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletServiceStatus) DeepCopyInto(out *KlusterletServiceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletServiceStatus.
func (in *KlusterletServiceStatus) DeepCopy() *KlusterletServiceStatus {
	if in == nil {
		return nil
	}
	out := new(KlusterletServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletTillerIntegrationSpec) DeepCopyInto(out *KlusterletTillerIntegrationSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletTillerIntegrationSpec.
func (in *KlusterletTillerIntegrationSpec) DeepCopy() *KlusterletTillerIntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(KlusterletTillerIntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletTopologyCollectorSpec) DeepCopyInto(out *KlusterletTopologyCollectorSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletTopologyCollectorSpec.
func (in *KlusterletTopologyCollectorSpec) DeepCopy() *KlusterletTopologyCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(KlusterletTopologyCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlusterletWorkManagerSpec) DeepCopyInto(out *KlusterletWorkManagerSpec) {
	*out = *in
	if in.ClusterLabels != nil {
		in, out := &in.ClusterLabels, &out.ClusterLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlusterletWorkManagerSpec.
func (in *KlusterletWorkManagerSpec) DeepCopy() *KlusterletWorkManagerSpec {
	if in == nil {
		return nil
	}
	out := new(KlusterletWorkManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchCollector) DeepCopyInto(out *SearchCollector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchCollector.
func (in *SearchCollector) DeepCopy() *SearchCollector {
	if in == nil {
		return nil
	}
	out := new(SearchCollector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SearchCollector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchCollectorList) DeepCopyInto(out *SearchCollectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SearchCollector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchCollectorList.
func (in *SearchCollectorList) DeepCopy() *SearchCollectorList {
	if in == nil {
		return nil
	}
	out := new(SearchCollectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SearchCollectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchCollectorSpec) DeepCopyInto(out *SearchCollectorSpec) {
	*out = *in
	out.TillerIntegration = in.TillerIntegration
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchCollectorSpec.
func (in *SearchCollectorSpec) DeepCopy() *SearchCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(SearchCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchCollectorStatus) DeepCopyInto(out *SearchCollectorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchCollectorStatus.
func (in *SearchCollectorStatus) DeepCopy() *SearchCollectorStatus {
	if in == nil {
		return nil
	}
	out := new(SearchCollectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchCollectorTillerIntegration) DeepCopyInto(out *SearchCollectorTillerIntegration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchCollectorTillerIntegration.
func (in *SearchCollectorTillerIntegration) DeepCopy() *SearchCollectorTillerIntegration {
	if in == nil {
		return nil
	}
	out := new(SearchCollectorTillerIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistry) DeepCopyInto(out *ServiceRegistry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistry.
func (in *ServiceRegistry) DeepCopy() *ServiceRegistry {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceRegistry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistryImage) DeepCopyInto(out *ServiceRegistryImage) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistryImage.
func (in *ServiceRegistryImage) DeepCopy() *ServiceRegistryImage {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistryImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistryList) DeepCopyInto(out *ServiceRegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistryList.
func (in *ServiceRegistryList) DeepCopy() *ServiceRegistryList {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceRegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistrySpec) DeepCopyInto(out *ServiceRegistrySpec) {
	*out = *in
	out.ServiceRegistry = in.ServiceRegistry
	out.CoreDNS = in.CoreDNS
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistrySpec.
func (in *ServiceRegistrySpec) DeepCopy() *ServiceRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistryStatus) DeepCopyInto(out *ServiceRegistryStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistryStatus.
func (in *ServiceRegistryStatus) DeepCopy() *ServiceRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tiller) DeepCopyInto(out *Tiller) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tiller.
func (in *Tiller) DeepCopy() *Tiller {
	if in == nil {
		return nil
	}
	out := new(Tiller)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tiller) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TillerList) DeepCopyInto(out *TillerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tiller, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TillerList.
func (in *TillerList) DeepCopy() *TillerList {
	if in == nil {
		return nil
	}
	out := new(TillerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TillerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TillerSpec) DeepCopyInto(out *TillerSpec) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TillerSpec.
func (in *TillerSpec) DeepCopy() *TillerSpec {
	if in == nil {
		return nil
	}
	out := new(TillerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TillerStatus) DeepCopyInto(out *TillerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TillerStatus.
func (in *TillerStatus) DeepCopy() *TillerStatus {
	if in == nil {
		return nil
	}
	out := new(TillerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyCollector) DeepCopyInto(out *TopologyCollector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyCollector.
func (in *TopologyCollector) DeepCopy() *TopologyCollector {
	if in == nil {
		return nil
	}
	out := new(TopologyCollector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TopologyCollector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyCollectorList) DeepCopyInto(out *TopologyCollectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TopologyCollector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyCollectorList.
func (in *TopologyCollectorList) DeepCopy() *TopologyCollectorList {
	if in == nil {
		return nil
	}
	out := new(TopologyCollectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TopologyCollectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyCollectorServiceAccount) DeepCopyInto(out *TopologyCollectorServiceAccount) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyCollectorServiceAccount.
func (in *TopologyCollectorServiceAccount) DeepCopy() *TopologyCollectorServiceAccount {
	if in == nil {
		return nil
	}
	out := new(TopologyCollectorServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyCollectorSpec) DeepCopyInto(out *TopologyCollectorSpec) {
	*out = *in
	out.ServiceAccount = in.ServiceAccount
	out.WeaveImage = in.WeaveImage
	out.CollectorImage = in.CollectorImage
	out.RouterImage = in.RouterImage
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyCollectorSpec.
func (in *TopologyCollectorSpec) DeepCopy() *TopologyCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(TopologyCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyCollectorStatus) DeepCopyInto(out *TopologyCollectorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyCollectorStatus.
func (in *TopologyCollectorStatus) DeepCopy() *TopologyCollectorStatus {
	if in == nil {
		return nil
	}
	out := new(TopologyCollectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManager) DeepCopyInto(out *WorkManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManager.
func (in *WorkManager) DeepCopy() *WorkManager {
	if in == nil {
		return nil
	}
	out := new(WorkManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManagerConfig) DeepCopyInto(out *WorkManagerConfig) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManagerConfig.
func (in *WorkManagerConfig) DeepCopy() *WorkManagerConfig {
	if in == nil {
		return nil
	}
	out := new(WorkManagerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManagerIngress) DeepCopyInto(out *WorkManagerIngress) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManagerIngress.
func (in *WorkManagerIngress) DeepCopy() *WorkManagerIngress {
	if in == nil {
		return nil
	}
	out := new(WorkManagerIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManagerList) DeepCopyInto(out *WorkManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManagerList.
func (in *WorkManagerList) DeepCopy() *WorkManagerList {
	if in == nil {
		return nil
	}
	out := new(WorkManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManagerPrometheusIntegration) DeepCopyInto(out *WorkManagerPrometheusIntegration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManagerPrometheusIntegration.
func (in *WorkManagerPrometheusIntegration) DeepCopy() *WorkManagerPrometheusIntegration {
	if in == nil {
		return nil
	}
	out := new(WorkManagerPrometheusIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManagerService) DeepCopyInto(out *WorkManagerService) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManagerService.
func (in *WorkManagerService) DeepCopy() *WorkManagerService {
	if in == nil {
		return nil
	}
	out := new(WorkManagerService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManagerSpec) DeepCopyInto(out *WorkManagerSpec) {
	*out = *in
	if in.ClusterLabels != nil {
		in, out := &in.ClusterLabels, &out.ClusterLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.TillerIntegration = in.TillerIntegration
	out.PrometheusIntegration = in.PrometheusIntegration
	out.Service = in.Service
	out.Ingress = in.Ingress
	out.WorkManagerConfig = in.WorkManagerConfig
	out.DeployableConfig = in.DeployableConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManagerSpec.
func (in *WorkManagerSpec) DeepCopy() *WorkManagerSpec {
	if in == nil {
		return nil
	}
	out := new(WorkManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManagerStatus) DeepCopyInto(out *WorkManagerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManagerStatus.
func (in *WorkManagerStatus) DeepCopy() *WorkManagerStatus {
	if in == nil {
		return nil
	}
	out := new(WorkManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManagerTillerIntegration) DeepCopyInto(out *WorkManagerTillerIntegration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManagerTillerIntegration.
func (in *WorkManagerTillerIntegration) DeepCopy() *WorkManagerTillerIntegration {
	if in == nil {
		return nil
	}
	out := new(WorkManagerTillerIntegration)
	in.DeepCopyInto(out)
	return out
}
