language: go

go:
  - "1.13.x"

services:
  - docker

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "eaoqOvvHVxcYIjrZKNjf5BC6o290X5ABWYTWcq/b2JFoklLCuLronloRQSH6DaSUjzTvhzluAyBelWQmCU4eT/owk2k66Zfa/sD7mRNJw1Eljv7OsOv0Z9dcW6OnVwSYTw9F4Px+pzpraf20ELm1qo0NboaGmdqH3aoBVxe9cn1/Ui9p1raWkmngh5RcYNTpKES0Bl3rn6c6HZKDhQl+wN+Wm+P+la8wedYIes+uz+ugeKf/vt//3PVWB0uvkrMGXtYMj/NQazjafjU65b4fgAybUac3ZmZId0ugRJMHcyYQpwjbizZE2Iy3ox3wKIB+1F2pwxjNg/cGHx2TXPOjxt8tV4OndQM3aT3kI1olsap8D65ItG+C80dJs93iVG/7V5OqvlijwnGIept+DC3DKv5Q12GKydWSAi8+MyUW9FdKDiOFIiBUckZlwPrGfv/N64EiK7unOew3b7/ywo4ujuxMzBm4vyEB75ABk1nk3U7KlSQzOOBhlOOSFHrTtJoWbDlPGGpaNiT8Bw5QUJWgZr6Dl644GY63krPb9w+bKdFLCQV0AgoxXHI1qY+iw2yTLF/jb80DWI63MLWdOAevZp0UnPXGfdyAkrXeHk7pxNJVrzsZ3/cjcK0iUYwzxXBvrAPoRgsyHvonKchOgHikPSLCS2DqEuXdtL/NV0IXJ1o="

stages:
  - build
  - unit-test
  - functional-test
  - release-ff
  - publish

before_script:
  - git config --global url.git@github.com:open-cluster-management/.insteadOf https://github.com/open-cluster-management/
  - make init

jobs:
  include:
    - stage: build
      name: "Run all checks, unit tests, build and push image"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - ./build/travis.sh   # to remove overhead and keep output clean
        - make security/scans

    - stage: build
      name: "build and push e2e image"
      if: type = pull_request
      script:
        - export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}-e2e"
        - export COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/build/build-e2e.sh 
        - ./build/travis.sh

    - stage: unit-test
      name: "Run unit tests"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make sonar/go

    - stage: functional-test
      name: "Run functional-test"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make component/init
        - make build-coverage
        - make component/test/functional

    - stage: release-ff
      name: "Push commits to current release branch"
      if: type = push AND branch =~ /^master$/
      script:
        - make
        - make release-ff

    - stage: publish
      name: "Publish Image"
      if: type = push AND branch =~ /^release-[0-9]+\..*$/
      script:
        - make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}
    #   after_script:
    #     - test "$TRAVIS_PULL_REQUEST" = "false" && test "$TRAVIS_TEST_RESULT" = "1" && ./build/slack-notification.sh || echo "Slack notification not sent"
