apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .ManagedClusterName }}"
  namespace: "{{ .ManagedClusterNamespace }}"
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - deployables
  - channels
  - channels/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - deployables/status
  verbs:
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - {{ .ManagedClusterAddonName }}
  verbs:
  - get
  - list
  - patch
  - update
  - watch