apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .ManagedClusterName }}"
  namespace: "{{ .ManagedClusterNamespace }}"
rules:
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - {{ .ManagedClusterAddonName }}
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create