kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .ManagedClusterName }}"
  namespace: "{{ .ManagedClusterNamespace }}"
subjects:
- kind: ServiceAccount
  name: "{{ .ServiceAccountName }}"
  namespace: "{{ .ManagedClusterNamespace }}"
roleRef:
  kind: Role
  name: "{{ .ManagedClusterName }}"
  apiGroup: rbac.authorization.k8s.io