# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .ManagedClusterName }}"
  namespace: "{{ .ManagedClusterNamespace }}"
rules:
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["action.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["view.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["internal.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - {{ .ManagedClusterAddonName }}
  resources:
  - leases
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create