apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workmanagers.multicloud.ibm.com
spec:
  group: multicloud.ibm.com
  names:
    kind: WorkManager
    listKind: WorkManagerList
    plural: workmanagers
    singular: workmanager
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: WorkManager is the Schema for the workmanagers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: WorkManagerSpec defines the desired state of WorkManager
          properties:
            clusterLabels:
              additionalProperties:
                type: string
              type: object
            clusterName:
              minLength: 1
              type: string
            clusterNamespace:
              minLength: 1
              type: string
            connectionManager:
              minLength: 1
              type: string
            fullnameOverride:
              minLength: 1
              type: string
            imagePullSecret:
              type: string
            ingress:
              description: WorkManagerIngress defines ingress configuration for WorkManager
              properties:
                host:
                  type: string
                port:
                  type: string
                type:
                  enum:
                  - Ingress
                  - Route
                  - None
                  type: string
              required:
              - host
              - port
              - type
              type: object
            prometheusIntegration:
              description: WorkManagerPrometheusIntegration defines prometheus integration
                parameters
              properties:
                enabled:
                  type: boolean
                scrapeTarget:
                  type: string
                secret:
                  type: string
                service:
                  type: string
                useBearerToken:
                  type: boolean
              required:
              - enabled
              - scrapeTarget
              - secret
              - service
              - useBearerToken
              type: object
            service:
              description: WorkManagerService defines service integration parameters
              properties:
                type:
                  enum:
                  - ClusterIP
                  - NodePort
                  - LoadBalancer
                  type: string
              required:
              - type
              type: object
            workManager:
              description: WorkManagerConfig defines work-manager container configuration
                parameters
              properties:
                enabled:
                  type: boolean
                image:
                  description: Image defines the image to pull for a container
                  properties:
                    pullPolicy:
                      description: PullPolicy describes a policy for if/when to pull
                        a container image
                      type: string
                    repository:
                      minLength: 1
                      type: string
                    tag:
                      minLength: 1
                      type: string
                  type: object
              required:
              - enabled
              - image
              type: object
          required:
          - clusterLabels
          - clusterName
          - clusterNamespace
          - connectionManager
          - fullnameOverride
          - ingress
          - prometheusIntegration
          - service
          type: object
        status:
          description: WorkManagerStatus defines the observed state of WorkManager
          type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
