apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: connectionmanagers.multicloud.ibm.com
spec:
  group: multicloud.ibm.com
  names:
    kind: ConnectionManager
    listKind: ConnectionManagerList
    plural: connectionmanagers
    singular: connectionmanager
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ConnectionManager is the Schema for the connectionmanagers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ConnectionManagerSpec defines the desired state of ConnectionManager
          properties:
            bootstrapConfig:
              additionalProperties:
                type: string
              type: object
            clusterName:
              minLength: 1
              type: string
            clusterNamespace:
              minLength: 1
              type: string
            fullnameOverride:
              minLength: 1
              type: string
            image:
              description: Image defines the image to pull for a container
              properties:
                pullPolicy:
                  description: PullPolicy describes a policy for if/when to pull a
                    container image
                  type: string
                repository:
                  minLength: 1
                  type: string
                tag:
                  minLength: 1
                  type: string
              type: object
            imagePullSecret:
              type: string
          required:
          - bootstrapConfig
          - clusterName
          - clusterNamespace
          - fullnameOverride
          type: object
        status:
          description: ConnectionManagerStatus defines the observed state of ConnectionManager
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
