apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certmanagers.multicloud.ibm.com
spec:
  group: multicloud.ibm.com
  names:
    kind: CertManager
    listKind: CertManagerList
    plural: certmanagers
    singular: certmanager
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CertManager is the Schema for the certmanagers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CertManagerSpec defines the desired state of CertManager
          properties:
            clusterResourceNamespace:
              minLength: 1
              type: string
            fullnameOverride:
              minLength: 1
              type: string
            image:
              description: Image defines the image to pull for a container
              properties:
                pullPolicy:
                  description: PullPolicy describes a policy for if/when to pull a
                    container image
                  type: string
                repository:
                  minLength: 1
                  type: string
                tag:
                  minLength: 1
                  type: string
              type: object
            policy-controller:
              description: CertManagerPolicyControllerSpec defines policy-controller
                enabledment in ICP certmanager chart
              properties:
                enabled:
                  type: boolean
              required:
              - enabled
              type: object
            serviceAccount:
              description: CertManagerServiceAccount defines service account configuration
                in the spec
              properties:
                name:
                  minLength: 1
                  type: string
              required:
              - name
              type: object
          required:
          - clusterResourceNamespace
          - fullnameOverride
          - policy-controller
          - serviceAccount
          type: object
        status:
          description: CertManagerStatus defines the observed state of CertManager
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
