apiVersion: multicloud.ibm.com/v1beta1
kind: Endpoint
metadata:
  name: endpoint
spec:
  clusterName: cluster-name
  clusterNamespace: cluster-namespace
  version: latest
  imagePullSecret: multicluster-endpoint-operator-pull-secret
  imageRegistry: hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom
  imageNamePostfix: -amd64
  imagePullPolicy: Always

  clusterLabels:
    cloud: "IBM"
    vendor: "ICP"
    environment: "Dev"
    region: "US"
    datacenter: "toronto"
    owner: "marketing"

  bootstrapConfig:
    hubSecret: multicluster-endpoint/klusterlet-bootstrap

  tillerIntegration:
    enabled: true

  prometheusIntegration:
    enabled: true

  topologyCollector:
    enabled: true
    updateInterval: 16

  applicationManager:
    enabled: true

  searchCollector:
    enabled: true

  policyController:
    enabled: true

  serviceRegistry:
    enabled: false
    coredns:
      dnsSuffix: "mcm.svc"
      plugins: "kube-service"
      clusterProxyIP: ""
