apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iampoliciescontroller.multicloud.ibm.com
spec:
  group: multicloud.ibm.com
  names:
    kind: IAMPolicyController
    listKind: IAMPolicyControllerList
    plural: iampoliciescontroller
    singular: iampolicycontroller
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: IAMPolicyController is the Schema for the iampolicycontroller API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: IAMPolicyControllerSpec defines the desired state of IAMPolicyController
          properties:
            clusterName:
              minLength: 1
              type: string
            clusterNamespace:
              minLength: 1
              type: string
            connectionManager:
              minLength: 1
              type: string
            fullnameOverride:
              minLength: 1
              type: string
            image:
              description: Image defines the image to pull for a container
              properties:
                pullPolicy:
                  description: PullPolicy describes a policy for if/when to pull a
                    container image
                  type: string
                repository:
                  minLength: 1
                  type: string
                tag:
                  minLength: 1
                  type: string
              type: object
            imagePullSecret:
              type: string
            ocp:
              type: boolean
          required:
          - clusterName
          - clusterNamespace
          - connectionManager
          - fullnameOverride
          type: object
        status:
          description: IAMPolicyControllerStatus defines the observed state of IAMPolicyController
          type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
