apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .ManagedClusterName }}"
  namespace: "{{ .ManagedClusterNamespace }}"
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch