apiVersion: apps/v1
kind: Deployment
metadata:
  name: klusterlet-operator
  namespace: klusterlet
spec:
  replicas: 1
  selector:
    matchLabels:
      name: klusterlet-operator
  template:
    metadata:
      labels:
        name: klusterlet-operator
    spec:
      serviceAccountName: klusterlet-operator
      containers:
        - name: klusterlet-operator
          # Replace this with the built image name
          image: REPLACE_NAME
          command:
          - klusterlet-operator
          imagePullPolicy: IfNotPresent
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "klusterlet-operator"
