---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-multicluster-endpoint-operator
  namespace: multicluster-endpoint
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ibm-multicluster-endpoint-operator
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-multicluster-endpoint-operator
subjects:
- kind: ServiceAccount
  name: ibm-multicluster-endpoint-operator
  namespace: multicluster-endpoint
roleRef:
  kind: ClusterRole
  name: ibm-multicluster-endpoint-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ibm-multicluster-endpoint-operator
  namespace: multicluster-endpoint
spec:
  selector:
    matchLabels:
      name: ibm-multicluster-endpoint-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: ibm-multicluster-endpoint-operator
    spec:
      containers:
      - command:
        - ibm-klusterlet-operator
        args:
        - "--zap-devel=true"
        env:
        - name: WATCH_NAMESPACE
        - name: OPERATOR_NAME
          value: ibm-klusterlet-operator
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom/icp-multicluster-endpoint-operator-amd64:latest
        imagePullPolicy: Always
        name: ibm-multicluster-endpoint-operator
        resources: {}
      imagePullSecrets:
      - name: multicluster-endpoint-operator-pull-secret
      serviceAccountName: ibm-multicluster-endpoint-operator
status: {}
