apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-operator
  namespace: multicluster-endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      name: endpoint-operator
  template:
    metadata:
      labels:
        name: endpoint-operator
    spec:
      serviceAccountName: endpoint-operator
      containers:
        - name: endpoint-operator
          # Replace this with the built image name
          image: REPLACE_NAME
          command:
          - endpoint-operator
          imagePullPolicy: IfNotPresent
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "endpoint-operator"
