kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoint-operator
subjects:
- kind: ServiceAccount
  name: endpoint-operator
  namespace: multicluster-endpoint
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io