apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: open-cluster-management:klusterlet-addon-controller
  namespace: open-cluster-management
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - klusterlets
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - klusterlet-addon-controller
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - agent.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  - managedclusters/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestworks
  - manifestworks/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# appmgr
- apiGroups:
  - compliance.mcm.ibm.com
  resources:
  - compliances
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.mcm.ibm.com
  resources:
  - policies
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - klusterlets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - update
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - deployables
  - channels
  - channels/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - deployables/status
  verbs:
  - patch
  - update
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["action.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["view.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["internal.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["mcm.ibm.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["proxy.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["policy.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]