apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ibm-klusterlet-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - ibm-klusterlet-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - klusterlet.mcm.ibm.com
  resources:
  - '*'
  - tillers
  - connectionmanagers
  - workmanagers
  - searchcollectors
  - policycontrollers
  verbs:
  - '*'
- apiGroups:
  - multicloud.ibm.com
  resources:
  - '*'
  - certmanagers
  - connectionmanagers
  - policycontrollers
  - searchcollectors
  - serviceregistries
  - tillers
  - topologycollectors
  - workmanagers
  verbs:
  - '*'
