# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: ServiceAccount
metadata:
  name: klusterlet-addon-controller
  namespace: open-cluster-management
imagePullSecrets:
- name: multicloud-image-pull-secret
