apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: klusterlet-addon-controller-validating-webhook
webhooks:
- name: klusterletaddonconfig.validating-webhook.open-cluster-management.io
  failurePolicy: Fail
  clientConfig:
    service:
      # reach the webhook via the registered aggregated API
      namespace: open-cluster-management
      name: klusterlet-addon-webhook
      path: /validate-v1-klusterletaddonconfig
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - agent.open-cluster-management.io
    apiVersions:
    - "*"
    resources:
    - klusterletaddonconfigs
    scope:     "Namespaced"
  admissionReviewVersions: ["v1beta1"]
  sideEffects: None
  timeoutSeconds: 5