// +build !ignore_autogenerated

// IBM Confidential
// OCO Source Materials
// (C) Copyright IBM Corporation 2020 All Rights Reserved
// The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

// Code generated by operator-sdk. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationManager) DeepCopyInto(out *ApplicationManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationManager.
func (in *ApplicationManager) DeepCopy() *ApplicationManager {
	if in == nil {
		return nil
	}
	out := new(ApplicationManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationManagerDeployableSpec) DeepCopyInto(out *ApplicationManagerDeployableSpec) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationManagerDeployableSpec.
func (in *ApplicationManagerDeployableSpec) DeepCopy() *ApplicationManagerDeployableSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationManagerDeployableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationManagerList) DeepCopyInto(out *ApplicationManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationManagerList.
func (in *ApplicationManagerList) DeepCopy() *ApplicationManagerList {
	if in == nil {
		return nil
	}
	out := new(ApplicationManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationManagerSpec) DeepCopyInto(out *ApplicationManagerSpec) {
	*out = *in
	out.DeployableSpec = in.DeployableSpec
	out.SubscriptionSpec = in.SubscriptionSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationManagerSpec.
func (in *ApplicationManagerSpec) DeepCopy() *ApplicationManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationManagerStatus) DeepCopyInto(out *ApplicationManagerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationManagerStatus.
func (in *ApplicationManagerStatus) DeepCopy() *ApplicationManagerStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationManagerSubscriptionSpec) DeepCopyInto(out *ApplicationManagerSubscriptionSpec) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationManagerSubscriptionSpec.
func (in *ApplicationManagerSubscriptionSpec) DeepCopy() *ApplicationManagerSubscriptionSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationManagerSubscriptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManager) DeepCopyInto(out *CertManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManager.
func (in *CertManager) DeepCopy() *CertManager {
	if in == nil {
		return nil
	}
	out := new(CertManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerList) DeepCopyInto(out *CertManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerList.
func (in *CertManagerList) DeepCopy() *CertManagerList {
	if in == nil {
		return nil
	}
	out := new(CertManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerPolicyControllerSpec) DeepCopyInto(out *CertManagerPolicyControllerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerPolicyControllerSpec.
func (in *CertManagerPolicyControllerSpec) DeepCopy() *CertManagerPolicyControllerSpec {
	if in == nil {
		return nil
	}
	out := new(CertManagerPolicyControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerServiceAccount) DeepCopyInto(out *CertManagerServiceAccount) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerServiceAccount.
func (in *CertManagerServiceAccount) DeepCopy() *CertManagerServiceAccount {
	if in == nil {
		return nil
	}
	out := new(CertManagerServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpec) DeepCopyInto(out *CertManagerSpec) {
	*out = *in
	out.Image = in.Image
	out.ServiceAccount = in.ServiceAccount
	out.PolicyController = in.PolicyController
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpec.
func (in *CertManagerSpec) DeepCopy() *CertManagerSpec {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerStatus) DeepCopyInto(out *CertManagerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerStatus.
func (in *CertManagerStatus) DeepCopy() *CertManagerStatus {
	if in == nil {
		return nil
	}
	out := new(CertManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionManager) DeepCopyInto(out *ConnectionManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionManager.
func (in *ConnectionManager) DeepCopy() *ConnectionManager {
	if in == nil {
		return nil
	}
	out := new(ConnectionManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectionManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionManagerList) DeepCopyInto(out *ConnectionManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConnectionManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionManagerList.
func (in *ConnectionManagerList) DeepCopy() *ConnectionManagerList {
	if in == nil {
		return nil
	}
	out := new(ConnectionManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectionManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionManagerSpec) DeepCopyInto(out *ConnectionManagerSpec) {
	*out = *in
	if in.BootStrapConfig != nil {
		in, out := &in.BootStrapConfig, &out.BootStrapConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionManagerSpec.
func (in *ConnectionManagerSpec) DeepCopy() *ConnectionManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionManagerStatus) DeepCopyInto(out *ConnectionManagerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionManagerStatus.
func (in *ConnectionManagerStatus) DeepCopy() *ConnectionManagerStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectionManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreDNSImage) DeepCopyInto(out *CoreDNSImage) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreDNSImage.
func (in *CoreDNSImage) DeepCopy() *CoreDNSImage {
	if in == nil {
		return nil
	}
	out := new(CoreDNSImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint.
func (in *Endpoint) DeepCopy() *Endpoint {
	if in == nil {
		return nil
	}
	out := new(Endpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Endpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointApplicationManagerSpec) DeepCopyInto(out *EndpointApplicationManagerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointApplicationManagerSpec.
func (in *EndpointApplicationManagerSpec) DeepCopy() *EndpointApplicationManagerSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointApplicationManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointConnectionManagerSpec) DeepCopyInto(out *EndpointConnectionManagerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointConnectionManagerSpec.
func (in *EndpointConnectionManagerSpec) DeepCopy() *EndpointConnectionManagerSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointConnectionManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointList) DeepCopyInto(out *EndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Endpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointList.
func (in *EndpointList) DeepCopy() *EndpointList {
	if in == nil {
		return nil
	}
	out := new(EndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointPolicyControllerSpec) DeepCopyInto(out *EndpointPolicyControllerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointPolicyControllerSpec.
func (in *EndpointPolicyControllerSpec) DeepCopy() *EndpointPolicyControllerSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointPolicyControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointPrometheusIntegrationSpec) DeepCopyInto(out *EndpointPrometheusIntegrationSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointPrometheusIntegrationSpec.
func (in *EndpointPrometheusIntegrationSpec) DeepCopy() *EndpointPrometheusIntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointPrometheusIntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSearchCollectorSpec) DeepCopyInto(out *EndpointSearchCollectorSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSearchCollectorSpec.
func (in *EndpointSearchCollectorSpec) DeepCopy() *EndpointSearchCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointSearchCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointServiceRegistrySpec) DeepCopyInto(out *EndpointServiceRegistrySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointServiceRegistrySpec.
func (in *EndpointServiceRegistrySpec) DeepCopy() *EndpointServiceRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(EndpointServiceRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSpec) DeepCopyInto(out *EndpointSpec) {
	*out = *in
	if in.ClusterLabels != nil {
		in, out := &in.ClusterLabels, &out.ClusterLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.BootStrapConfig != nil {
		in, out := &in.BootStrapConfig, &out.BootStrapConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.PrometheusIntegration = in.PrometheusIntegration
	out.TopologyCollectorConfig = in.TopologyCollectorConfig
	out.SearchCollectorConfig = in.SearchCollectorConfig
	out.PolicyController = in.PolicyController
	out.ServiceRegistryConfig = in.ServiceRegistryConfig
	out.ApplicationManagerConfig = in.ApplicationManagerConfig
	out.ConnectionManagerConfig = in.ConnectionManagerConfig
	if in.ComponentsImagesTag != nil {
		in, out := &in.ComponentsImagesTag, &out.ComponentsImagesTag
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSpec.
func (in *EndpointSpec) DeepCopy() *EndpointSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointStatus) DeepCopyInto(out *EndpointStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointStatus.
func (in *EndpointStatus) DeepCopy() *EndpointStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointTopologyCollectorSpec) DeepCopyInto(out *EndpointTopologyCollectorSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointTopologyCollectorSpec.
func (in *EndpointTopologyCollectorSpec) DeepCopy() *EndpointTopologyCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointTopologyCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointWorkManagerSpec) DeepCopyInto(out *EndpointWorkManagerSpec) {
	*out = *in
	if in.ClusterLabels != nil {
		in, out := &in.ClusterLabels, &out.ClusterLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointWorkManagerSpec.
func (in *EndpointWorkManagerSpec) DeepCopy() *EndpointWorkManagerSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointWorkManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitoring) DeepCopyInto(out *Monitoring) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitoring.
func (in *Monitoring) DeepCopy() *Monitoring {
	if in == nil {
		return nil
	}
	out := new(Monitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Monitoring) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringAlertmanager) DeepCopyInto(out *MonitoringAlertmanager) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringAlertmanager.
func (in *MonitoringAlertmanager) DeepCopy() *MonitoringAlertmanager {
	if in == nil {
		return nil
	}
	out := new(MonitoringAlertmanager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringAlertruleController) DeepCopyInto(out *MonitoringAlertruleController) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringAlertruleController.
func (in *MonitoringAlertruleController) DeepCopy() *MonitoringAlertruleController {
	if in == nil {
		return nil
	}
	out := new(MonitoringAlertruleController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringCollectdExporter) DeepCopyInto(out *MonitoringCollectdExporter) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringCollectdExporter.
func (in *MonitoringCollectdExporter) DeepCopy() *MonitoringCollectdExporter {
	if in == nil {
		return nil
	}
	out := new(MonitoringCollectdExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfigmapReload) DeepCopyInto(out *MonitoringConfigmapReload) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfigmapReload.
func (in *MonitoringConfigmapReload) DeepCopy() *MonitoringConfigmapReload {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfigmapReload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringCurl) DeepCopyInto(out *MonitoringCurl) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringCurl.
func (in *MonitoringCurl) DeepCopy() *MonitoringCurl {
	if in == nil {
		return nil
	}
	out := new(MonitoringCurl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringElasticsearchExporter) DeepCopyInto(out *MonitoringElasticsearchExporter) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringElasticsearchExporter.
func (in *MonitoringElasticsearchExporter) DeepCopy() *MonitoringElasticsearchExporter {
	if in == nil {
		return nil
	}
	out := new(MonitoringElasticsearchExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringGrafana) DeepCopyInto(out *MonitoringGrafana) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringGrafana.
func (in *MonitoringGrafana) DeepCopy() *MonitoringGrafana {
	if in == nil {
		return nil
	}
	out := new(MonitoringGrafana)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringKubeStateMetrics) DeepCopyInto(out *MonitoringKubeStateMetrics) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringKubeStateMetrics.
func (in *MonitoringKubeStateMetrics) DeepCopy() *MonitoringKubeStateMetrics {
	if in == nil {
		return nil
	}
	out := new(MonitoringKubeStateMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringList) DeepCopyInto(out *MonitoringList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Monitoring, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringList.
func (in *MonitoringList) DeepCopy() *MonitoringList {
	if in == nil {
		return nil
	}
	out := new(MonitoringList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringNodeExporter) DeepCopyInto(out *MonitoringNodeExporter) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringNodeExporter.
func (in *MonitoringNodeExporter) DeepCopy() *MonitoringNodeExporter {
	if in == nil {
		return nil
	}
	out := new(MonitoringNodeExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringPrometheus) DeepCopyInto(out *MonitoringPrometheus) {
	*out = *in
	out.Image = in.Image
	out.EtcdTarget = in.EtcdTarget
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringPrometheus.
func (in *MonitoringPrometheus) DeepCopy() *MonitoringPrometheus {
	if in == nil {
		return nil
	}
	out := new(MonitoringPrometheus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringPrometheusConfigReloader) DeepCopyInto(out *MonitoringPrometheusConfigReloader) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringPrometheusConfigReloader.
func (in *MonitoringPrometheusConfigReloader) DeepCopy() *MonitoringPrometheusConfigReloader {
	if in == nil {
		return nil
	}
	out := new(MonitoringPrometheusConfigReloader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringPrometheusEtcdTarget) DeepCopyInto(out *MonitoringPrometheusEtcdTarget) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringPrometheusEtcdTarget.
func (in *MonitoringPrometheusEtcdTarget) DeepCopy() *MonitoringPrometheusEtcdTarget {
	if in == nil {
		return nil
	}
	out := new(MonitoringPrometheusEtcdTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringPrometheusOperator) DeepCopyInto(out *MonitoringPrometheusOperator) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringPrometheusOperator.
func (in *MonitoringPrometheusOperator) DeepCopy() *MonitoringPrometheusOperator {
	if in == nil {
		return nil
	}
	out := new(MonitoringPrometheusOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringPrometheusOperatorController) DeepCopyInto(out *MonitoringPrometheusOperatorController) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringPrometheusOperatorController.
func (in *MonitoringPrometheusOperatorController) DeepCopy() *MonitoringPrometheusOperatorController {
	if in == nil {
		return nil
	}
	out := new(MonitoringPrometheusOperatorController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringRouter) DeepCopyInto(out *MonitoringRouter) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringRouter.
func (in *MonitoringRouter) DeepCopy() *MonitoringRouter {
	if in == nil {
		return nil
	}
	out := new(MonitoringRouter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
	out.TLS = in.TLS
	out.Prometheus = in.Prometheus
	out.Alertmanager = in.Alertmanager
	out.Grafana = in.Grafana
	out.KubeStateMetrics = in.KubeStateMetrics
	out.NodeExporter = in.NodeExporter
	out.CollectdExporter = in.CollectdExporter
	out.ElasticsearchExporter = in.ElasticsearchExporter
	out.ConfigmapReload = in.ConfigmapReload
	out.Router = in.Router
	out.PrometheusOperatorController = in.PrometheusOperatorController
	out.PrometheusOperator = in.PrometheusOperator
	out.PrometheusConfigReloader = in.PrometheusConfigReloader
	out.Curl = in.Curl
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringStatus) DeepCopyInto(out *MonitoringStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringStatus.
func (in *MonitoringStatus) DeepCopy() *MonitoringStatus {
	if in == nil {
		return nil
	}
	out := new(MonitoringStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringTLS) DeepCopyInto(out *MonitoringTLS) {
	*out = *in
	out.CA = in.CA
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringTLS.
func (in *MonitoringTLS) DeepCopy() *MonitoringTLS {
	if in == nil {
		return nil
	}
	out := new(MonitoringTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringTLSCA) DeepCopyInto(out *MonitoringTLSCA) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringTLSCA.
func (in *MonitoringTLSCA) DeepCopy() *MonitoringTLSCA {
	if in == nil {
		return nil
	}
	out := new(MonitoringTLSCA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyController) DeepCopyInto(out *PolicyController) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyController.
func (in *PolicyController) DeepCopy() *PolicyController {
	if in == nil {
		return nil
	}
	out := new(PolicyController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyController) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyControllerList) DeepCopyInto(out *PolicyControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyController, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyControllerList.
func (in *PolicyControllerList) DeepCopy() *PolicyControllerList {
	if in == nil {
		return nil
	}
	out := new(PolicyControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyControllerSpec) DeepCopyInto(out *PolicyControllerSpec) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyControllerSpec.
func (in *PolicyControllerSpec) DeepCopy() *PolicyControllerSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyControllerStatus) DeepCopyInto(out *PolicyControllerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyControllerStatus.
func (in *PolicyControllerStatus) DeepCopy() *PolicyControllerStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchCollector) DeepCopyInto(out *SearchCollector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchCollector.
func (in *SearchCollector) DeepCopy() *SearchCollector {
	if in == nil {
		return nil
	}
	out := new(SearchCollector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SearchCollector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchCollectorList) DeepCopyInto(out *SearchCollectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SearchCollector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchCollectorList.
func (in *SearchCollectorList) DeepCopy() *SearchCollectorList {
	if in == nil {
		return nil
	}
	out := new(SearchCollectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SearchCollectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchCollectorSpec) DeepCopyInto(out *SearchCollectorSpec) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchCollectorSpec.
func (in *SearchCollectorSpec) DeepCopy() *SearchCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(SearchCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchCollectorStatus) DeepCopyInto(out *SearchCollectorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchCollectorStatus.
func (in *SearchCollectorStatus) DeepCopy() *SearchCollectorStatus {
	if in == nil {
		return nil
	}
	out := new(SearchCollectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistry) DeepCopyInto(out *ServiceRegistry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistry.
func (in *ServiceRegistry) DeepCopy() *ServiceRegistry {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceRegistry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistryImage) DeepCopyInto(out *ServiceRegistryImage) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistryImage.
func (in *ServiceRegistryImage) DeepCopy() *ServiceRegistryImage {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistryImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistryList) DeepCopyInto(out *ServiceRegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistryList.
func (in *ServiceRegistryList) DeepCopy() *ServiceRegistryList {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceRegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistrySpec) DeepCopyInto(out *ServiceRegistrySpec) {
	*out = *in
	out.ServiceRegistry = in.ServiceRegistry
	out.CoreDNS = in.CoreDNS
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistrySpec.
func (in *ServiceRegistrySpec) DeepCopy() *ServiceRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistryStatus) DeepCopyInto(out *ServiceRegistryStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistryStatus.
func (in *ServiceRegistryStatus) DeepCopy() *ServiceRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyCollector) DeepCopyInto(out *TopologyCollector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyCollector.
func (in *TopologyCollector) DeepCopy() *TopologyCollector {
	if in == nil {
		return nil
	}
	out := new(TopologyCollector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TopologyCollector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyCollectorList) DeepCopyInto(out *TopologyCollectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TopologyCollector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyCollectorList.
func (in *TopologyCollectorList) DeepCopy() *TopologyCollectorList {
	if in == nil {
		return nil
	}
	out := new(TopologyCollectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TopologyCollectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyCollectorServiceAccount) DeepCopyInto(out *TopologyCollectorServiceAccount) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyCollectorServiceAccount.
func (in *TopologyCollectorServiceAccount) DeepCopy() *TopologyCollectorServiceAccount {
	if in == nil {
		return nil
	}
	out := new(TopologyCollectorServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyCollectorSpec) DeepCopyInto(out *TopologyCollectorSpec) {
	*out = *in
	out.ServiceAccount = in.ServiceAccount
	out.WeaveImage = in.WeaveImage
	out.CollectorImage = in.CollectorImage
	out.RouterImage = in.RouterImage
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyCollectorSpec.
func (in *TopologyCollectorSpec) DeepCopy() *TopologyCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(TopologyCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyCollectorStatus) DeepCopyInto(out *TopologyCollectorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyCollectorStatus.
func (in *TopologyCollectorStatus) DeepCopy() *TopologyCollectorStatus {
	if in == nil {
		return nil
	}
	out := new(TopologyCollectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManager) DeepCopyInto(out *WorkManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManager.
func (in *WorkManager) DeepCopy() *WorkManager {
	if in == nil {
		return nil
	}
	out := new(WorkManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManagerConfig) DeepCopyInto(out *WorkManagerConfig) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManagerConfig.
func (in *WorkManagerConfig) DeepCopy() *WorkManagerConfig {
	if in == nil {
		return nil
	}
	out := new(WorkManagerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManagerIngress) DeepCopyInto(out *WorkManagerIngress) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManagerIngress.
func (in *WorkManagerIngress) DeepCopy() *WorkManagerIngress {
	if in == nil {
		return nil
	}
	out := new(WorkManagerIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManagerList) DeepCopyInto(out *WorkManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManagerList.
func (in *WorkManagerList) DeepCopy() *WorkManagerList {
	if in == nil {
		return nil
	}
	out := new(WorkManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManagerPrometheusIntegration) DeepCopyInto(out *WorkManagerPrometheusIntegration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManagerPrometheusIntegration.
func (in *WorkManagerPrometheusIntegration) DeepCopy() *WorkManagerPrometheusIntegration {
	if in == nil {
		return nil
	}
	out := new(WorkManagerPrometheusIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManagerService) DeepCopyInto(out *WorkManagerService) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManagerService.
func (in *WorkManagerService) DeepCopy() *WorkManagerService {
	if in == nil {
		return nil
	}
	out := new(WorkManagerService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManagerSpec) DeepCopyInto(out *WorkManagerSpec) {
	*out = *in
	if in.ClusterLabels != nil {
		in, out := &in.ClusterLabels, &out.ClusterLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.PrometheusIntegration = in.PrometheusIntegration
	out.Service = in.Service
	out.Ingress = in.Ingress
	out.WorkManagerConfig = in.WorkManagerConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManagerSpec.
func (in *WorkManagerSpec) DeepCopy() *WorkManagerSpec {
	if in == nil {
		return nil
	}
	out := new(WorkManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkManagerStatus) DeepCopyInto(out *WorkManagerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkManagerStatus.
func (in *WorkManagerStatus) DeepCopy() *WorkManagerStatus {
	if in == nil {
		return nil
	}
	out := new(WorkManagerStatus)
	in.DeepCopyInto(out)
	return out
}
