apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .ManagedClusterName }}"
  namespace: "{{ .ManagedClusterNamespace }}"
rules:
- verbs:
  - create
  apiGroups:
  - proxy.open-cluster-management.io
  resources:
  - clusterstatuses/aggregator