# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .ManagedClusterName }}"
  namespace: "{{ .ManagedClusterNamespace }}"
rules:
- verbs:
  - create
  apiGroups:
  - proxy.open-cluster-management.io
  resources:
  - clusterstatuses/aggregator
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - {{ .ManagedClusterAddonName }}
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create