# Copyright Contributors to the Open Cluster Management project

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: searchcollectors.agent.open-cluster-management.io
spec:
  group: agent.open-cluster-management.io
  names:
    kind: SearchCollector
    listKind: SearchCollectorList
    plural: searchcollectors
    singular: searchcollector
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: SearchCollector is the Schema for the searchcollectors API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SearchCollectorSpec defines the desired state of SearchCollector
            properties:
              clusterName:
                minLength: 1
                type: string
              clusterNamespace:
                minLength: 1
                type: string
              fullnameOverride:
                minLength: 1
                type: string
              global:
                description: GlobalValues defines the global values
                properties:
                  imageOverrides:
                    additionalProperties:
                      type: string
                    type: object
                  imagePullPolicy:
                    description: PullPolicy describes a policy for if/when to pull
                      a container image
                    type: string
                  imagePullSecret:
                    type: string
                type: object
              hubKubeconfigSecret:
                minLength: 1
                type: string
            required:
            - clusterName
            - clusterNamespace
            - fullnameOverride
            - hubKubeconfigSecret
            type: object
          status:
            description: SearchCollectorStatus defines the observed state of SearchCollector
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
